'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace ServiceReference5
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Result", [Namespace]:="http://schemas.datacontract.org/2004/07/JCCService"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Result
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AssocaiationGovernorate1Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AssocaiationStatus1Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AssocationName1Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AssocationNationalNo1Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AssociationRegNo1Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AssociationRegYear1Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AssociationType1Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AssoiationCapital1Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private GovernorateDesc1Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private StatusDesc1Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TypeDesc1Field As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property AssocaiationGovernorate1() As String
            Get
                Return Me.AssocaiationGovernorate1Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.AssocaiationGovernorate1Field, value) <> true) Then
                    Me.AssocaiationGovernorate1Field = value
                    Me.RaisePropertyChanged("AssocaiationGovernorate1")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property AssocaiationStatus1() As String
            Get
                Return Me.AssocaiationStatus1Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.AssocaiationStatus1Field, value) <> true) Then
                    Me.AssocaiationStatus1Field = value
                    Me.RaisePropertyChanged("AssocaiationStatus1")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property AssocationName1() As String
            Get
                Return Me.AssocationName1Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.AssocationName1Field, value) <> true) Then
                    Me.AssocationName1Field = value
                    Me.RaisePropertyChanged("AssocationName1")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property AssocationNationalNo1() As String
            Get
                Return Me.AssocationNationalNo1Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.AssocationNationalNo1Field, value) <> true) Then
                    Me.AssocationNationalNo1Field = value
                    Me.RaisePropertyChanged("AssocationNationalNo1")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property AssociationRegNo1() As String
            Get
                Return Me.AssociationRegNo1Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.AssociationRegNo1Field, value) <> true) Then
                    Me.AssociationRegNo1Field = value
                    Me.RaisePropertyChanged("AssociationRegNo1")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property AssociationRegYear1() As String
            Get
                Return Me.AssociationRegYear1Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.AssociationRegYear1Field, value) <> true) Then
                    Me.AssociationRegYear1Field = value
                    Me.RaisePropertyChanged("AssociationRegYear1")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property AssociationType1() As String
            Get
                Return Me.AssociationType1Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.AssociationType1Field, value) <> true) Then
                    Me.AssociationType1Field = value
                    Me.RaisePropertyChanged("AssociationType1")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property AssoiationCapital1() As String
            Get
                Return Me.AssoiationCapital1Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.AssoiationCapital1Field, value) <> true) Then
                    Me.AssoiationCapital1Field = value
                    Me.RaisePropertyChanged("AssoiationCapital1")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property GovernorateDesc1() As String
            Get
                Return Me.GovernorateDesc1Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.GovernorateDesc1Field, value) <> true) Then
                    Me.GovernorateDesc1Field = value
                    Me.RaisePropertyChanged("GovernorateDesc1")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property StatusDesc1() As String
            Get
                Return Me.StatusDesc1Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.StatusDesc1Field, value) <> true) Then
                    Me.StatusDesc1Field = value
                    Me.RaisePropertyChanged("StatusDesc1")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property TypeDesc1() As String
            Get
                Return Me.TypeDesc1Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.TypeDesc1Field, value) <> true) Then
                    Me.TypeDesc1Field = value
                    Me.RaisePropertyChanged("TypeDesc1")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="ServiceReference5.IJCCSrvV1")>  _
    Public Interface IJCCSrvV1
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IJCCSrvV1/GetAssociationsData", ReplyAction:="http://tempuri.org/IJCCSrvV1/GetAssociationsDataResponse")>  _
        Function GetAssociationsData(ByVal NATNO As String) As ServiceReference5.Result()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IJCCSrvV1/GetAssociationsData", ReplyAction:="http://tempuri.org/IJCCSrvV1/GetAssociationsDataResponse")>  _
        Function GetAssociationsDataAsync(ByVal NATNO As String) As System.Threading.Tasks.Task(Of ServiceReference5.Result())
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IJCCSrvV1Channel
        Inherits ServiceReference5.IJCCSrvV1, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class JCCSrvV1Client
        Inherits System.ServiceModel.ClientBase(Of ServiceReference5.IJCCSrvV1)
        Implements ServiceReference5.IJCCSrvV1
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function GetAssociationsData(ByVal NATNO As String) As ServiceReference5.Result() Implements ServiceReference5.IJCCSrvV1.GetAssociationsData
            Return MyBase.Channel.GetAssociationsData(NATNO)
        End Function
        
        Public Function GetAssociationsDataAsync(ByVal NATNO As String) As System.Threading.Tasks.Task(Of ServiceReference5.Result()) Implements ServiceReference5.IJCCSrvV1.GetAssociationsDataAsync
            Return MyBase.Channel.GetAssociationsDataAsync(NATNO)
        End Function
    End Class
End Namespace
