'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace ServiceReference6
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/FreeZones")>  _
    Partial Public Class FreeZonesExceptionFault
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private errorCodeField As System.Nullable(Of Integer)
        
        Private errorCodeFieldSpecified As Boolean
        
        Private errorDescField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=0)>  _
        Public Property errorCode() As System.Nullable(Of Integer)
            Get
                Return Me.errorCodeField
            End Get
            Set
                Me.errorCodeField = value
                Me.RaisePropertyChanged("errorCode")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property errorCodeSpecified() As Boolean
            Get
                Return Me.errorCodeFieldSpecified
            End Get
            Set
                Me.errorCodeFieldSpecified = value
                Me.RaisePropertyChanged("errorCodeSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=1)>  _
        Public Property errorDesc() As String
            Get
                Return Me.errorDescField
            End Get
            Set
                Me.errorDescField = value
                Me.RaisePropertyChanged("errorDesc")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="ServiceReference6.FreeZonesServiceInterface")>  _
    Public Interface FreeZonesServiceInterface
        
        'CODEGEN: Generating message contract since the operation getCommercialRecord is neither RPC nor document wrapped.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/FreeZonesServiceInterface/getCommercialRecordRequest", ReplyAction:="http://tempuri.org/FreeZonesServiceInterface/getCommercialRecordResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(ServiceReference6.FreeZonesExceptionFault), Action:="http://tempuri.org/FreeZonesServiceInterface/getWellLicenseFreeZonesExceptionFaul"& _ 
            "t", Name:="FreeZonesExceptionFault", [Namespace]:="http://schemas.datacontract.org/2004/07/FreeZones"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function getCommercialRecord(ByVal request As ServiceReference6.getCommercialRecordRequest1) As ServiceReference6.getCommercialRecordResponse1
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/FreeZonesServiceInterface/getCommercialRecordRequest", ReplyAction:="http://tempuri.org/FreeZonesServiceInterface/getCommercialRecordResponse")>  _
        Function getCommercialRecordAsync(ByVal request As ServiceReference6.getCommercialRecordRequest1) As System.Threading.Tasks.Task(Of ServiceReference6.getCommercialRecordResponse1)
        
        'CODEGEN: Generating message contract since the operation getVocationalLicense is neither RPC nor document wrapped.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/FreeZonesServiceInterface/getVocationalLicenseRequest", ReplyAction:="http://tempuri.org/FreeZonesServiceInterface/getVocationalLicenseResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(ServiceReference6.FreeZonesExceptionFault), Action:="http://tempuri.org/FreeZonesServiceInterface/getVocationalLicenseFaultMessage", Name:="FreeZonesExceptionFault", [Namespace]:="http://schemas.datacontract.org/2004/07/FreeZones"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function getVocationalLicense(ByVal request As ServiceReference6.getVocationalLicenseRequest1) As ServiceReference6.getVocationalLicenseResponse1
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/FreeZonesServiceInterface/getVocationalLicenseRequest", ReplyAction:="http://tempuri.org/FreeZonesServiceInterface/getVocationalLicenseResponse")>  _
        Function getVocationalLicenseAsync(ByVal request As ServiceReference6.getVocationalLicenseRequest1) As System.Threading.Tasks.Task(Of ServiceReference6.getVocationalLicenseResponse1)
    End Interface
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://tempuri.org/")>  _
    Partial Public Class getCommercialRecordRequest
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private estIdNoField As Long
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property estIdNo() As Long
            Get
                Return Me.estIdNoField
            End Get
            Set
                Me.estIdNoField = value
                Me.RaisePropertyChanged("estIdNo")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://tempuri.org/")>  _
    Partial Public Class getCommercialRecordResponse
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private estIdNoField As Long
        
        Private estNameField As String
        
        Private shareCapitalField As Double
        
        Private estStatusCodeField As Long
        
        Private estStatusDescField As String
        
        Private ownersNatNoField() As Long
        
        Private ownersNameField() As String
        
        Private economicActivityCodeField As Long
        
        Private economicActivityDescField As String
        
        Private mobileNoField As String
        
        Private faxNoField As String
        
        Private postNoField As String
        
        Private guaranteeStatusField As Integer
        
        Private resultMessageField As getCommercialRecordResponseResultMessage
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property estIdNo() As Long
            Get
                Return Me.estIdNoField
            End Get
            Set
                Me.estIdNoField = value
                Me.RaisePropertyChanged("estIdNo")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property estName() As String
            Get
                Return Me.estNameField
            End Get
            Set
                Me.estNameField = value
                Me.RaisePropertyChanged("estName")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property shareCapital() As Double
            Get
                Return Me.shareCapitalField
            End Get
            Set
                Me.shareCapitalField = value
                Me.RaisePropertyChanged("shareCapital")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>  _
        Public Property estStatusCode() As Long
            Get
                Return Me.estStatusCodeField
            End Get
            Set
                Me.estStatusCodeField = value
                Me.RaisePropertyChanged("estStatusCode")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=4)>  _
        Public Property estStatusDesc() As String
            Get
                Return Me.estStatusDescField
            End Get
            Set
                Me.estStatusDescField = value
                Me.RaisePropertyChanged("estStatusDesc")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("ownersNatNo", Order:=5)>  _
        Public Property ownersNatNo() As Long()
            Get
                Return Me.ownersNatNoField
            End Get
            Set
                Me.ownersNatNoField = value
                Me.RaisePropertyChanged("ownersNatNo")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("ownersName", Order:=6)>  _
        Public Property ownersName() As String()
            Get
                Return Me.ownersNameField
            End Get
            Set
                Me.ownersNameField = value
                Me.RaisePropertyChanged("ownersName")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=7)>  _
        Public Property economicActivityCode() As Long
            Get
                Return Me.economicActivityCodeField
            End Get
            Set
                Me.economicActivityCodeField = value
                Me.RaisePropertyChanged("economicActivityCode")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=8)>  _
        Public Property economicActivityDesc() As String
            Get
                Return Me.economicActivityDescField
            End Get
            Set
                Me.economicActivityDescField = value
                Me.RaisePropertyChanged("economicActivityDesc")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=9)>  _
        Public Property mobileNo() As String
            Get
                Return Me.mobileNoField
            End Get
            Set
                Me.mobileNoField = value
                Me.RaisePropertyChanged("mobileNo")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=10)>  _
        Public Property faxNo() As String
            Get
                Return Me.faxNoField
            End Get
            Set
                Me.faxNoField = value
                Me.RaisePropertyChanged("faxNo")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=11)>  _
        Public Property postNo() As String
            Get
                Return Me.postNoField
            End Get
            Set
                Me.postNoField = value
                Me.RaisePropertyChanged("postNo")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=12)>  _
        Public Property guaranteeStatus() As Integer
            Get
                Return Me.guaranteeStatusField
            End Get
            Set
                Me.guaranteeStatusField = value
                Me.RaisePropertyChanged("guaranteeStatus")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=13)>  _
        Public Property resultMessage() As getCommercialRecordResponseResultMessage
            Get
                Return Me.resultMessageField
            End Get
            Set
                Me.resultMessageField = value
                Me.RaisePropertyChanged("resultMessage")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://tempuri.org/")>  _
    Partial Public Class getCommercialRecordResponseResultMessage
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private resultCodeField As Integer
        
        Private resultDescField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property resultCode() As Integer
            Get
                Return Me.resultCodeField
            End Get
            Set
                Me.resultCodeField = value
                Me.RaisePropertyChanged("resultCode")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property resultDesc() As String
            Get
                Return Me.resultDescField
            End Get
            Set
                Me.resultDescField = value
                Me.RaisePropertyChanged("resultDesc")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class getCommercialRecordRequest1
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public getCommercialRecordRequest As ServiceReference6.getCommercialRecordRequest
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal getCommercialRecordRequest As ServiceReference6.getCommercialRecordRequest)
            MyBase.New
            Me.getCommercialRecordRequest = getCommercialRecordRequest
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class getCommercialRecordResponse1
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public getCommercialRecordResponse As ServiceReference6.getCommercialRecordResponse
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal getCommercialRecordResponse As ServiceReference6.getCommercialRecordResponse)
            MyBase.New
            Me.getCommercialRecordResponse = getCommercialRecordResponse
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://tempuri.org/")>  _
    Partial Public Class getVocationalLicenseRequest
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private licenseNoField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property licenseNo() As String
            Get
                Return Me.licenseNoField
            End Get
            Set
                Me.licenseNoField = value
                Me.RaisePropertyChanged("licenseNo")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://tempuri.org/")>  _
    Partial Public Class getVocationalLicenseResponse
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private licenseNoField As String
        
        Private estIdNoField As Long
        
        Private commercialNameField As String
        
        Private licenseOwnerField As String
        
        Private investorNoField As Long
        
        Private licenseYearField As Integer
        
        Private issueDateField As Date
        
        Private expiryDateField As Date
        
        Private investmentTypeCodeField As Long
        
        Private investmentTypeDescField As String
        
        Private economicActivityCodeField As Long
        
        Private economicActivityDescField As String
        
        Private addressField As String
        
        Private districtNoField As Long
        
        Private guaranteeStatusField As Integer
        
        Private resultMessageField As getVocationalLicenseResponseResultMessage
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property licenseNo() As String
            Get
                Return Me.licenseNoField
            End Get
            Set
                Me.licenseNoField = value
                Me.RaisePropertyChanged("licenseNo")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property estIdNo() As Long
            Get
                Return Me.estIdNoField
            End Get
            Set
                Me.estIdNoField = value
                Me.RaisePropertyChanged("estIdNo")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property commercialName() As String
            Get
                Return Me.commercialNameField
            End Get
            Set
                Me.commercialNameField = value
                Me.RaisePropertyChanged("commercialName")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>  _
        Public Property licenseOwner() As String
            Get
                Return Me.licenseOwnerField
            End Get
            Set
                Me.licenseOwnerField = value
                Me.RaisePropertyChanged("licenseOwner")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=4)>  _
        Public Property investorNo() As Long
            Get
                Return Me.investorNoField
            End Get
            Set
                Me.investorNoField = value
                Me.RaisePropertyChanged("investorNo")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=5)>  _
        Public Property licenseYear() As Integer
            Get
                Return Me.licenseYearField
            End Get
            Set
                Me.licenseYearField = value
                Me.RaisePropertyChanged("licenseYear")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="date", Order:=6)>  _
        Public Property issueDate() As Date
            Get
                Return Me.issueDateField
            End Get
            Set
                Me.issueDateField = value
                Me.RaisePropertyChanged("issueDate")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="date", Order:=7)>  _
        Public Property expiryDate() As Date
            Get
                Return Me.expiryDateField
            End Get
            Set
                Me.expiryDateField = value
                Me.RaisePropertyChanged("expiryDate")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=8)>  _
        Public Property investmentTypeCode() As Long
            Get
                Return Me.investmentTypeCodeField
            End Get
            Set
                Me.investmentTypeCodeField = value
                Me.RaisePropertyChanged("investmentTypeCode")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=9)>  _
        Public Property investmentTypeDesc() As String
            Get
                Return Me.investmentTypeDescField
            End Get
            Set
                Me.investmentTypeDescField = value
                Me.RaisePropertyChanged("investmentTypeDesc")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=10)>  _
        Public Property economicActivityCode() As Long
            Get
                Return Me.economicActivityCodeField
            End Get
            Set
                Me.economicActivityCodeField = value
                Me.RaisePropertyChanged("economicActivityCode")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=11)>  _
        Public Property economicActivityDesc() As String
            Get
                Return Me.economicActivityDescField
            End Get
            Set
                Me.economicActivityDescField = value
                Me.RaisePropertyChanged("economicActivityDesc")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=12)>  _
        Public Property address() As String
            Get
                Return Me.addressField
            End Get
            Set
                Me.addressField = value
                Me.RaisePropertyChanged("address")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=13)>  _
        Public Property districtNo() As Long
            Get
                Return Me.districtNoField
            End Get
            Set
                Me.districtNoField = value
                Me.RaisePropertyChanged("districtNo")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=14)>  _
        Public Property guaranteeStatus() As Integer
            Get
                Return Me.guaranteeStatusField
            End Get
            Set
                Me.guaranteeStatusField = value
                Me.RaisePropertyChanged("guaranteeStatus")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=15)>  _
        Public Property resultMessage() As getVocationalLicenseResponseResultMessage
            Get
                Return Me.resultMessageField
            End Get
            Set
                Me.resultMessageField = value
                Me.RaisePropertyChanged("resultMessage")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://tempuri.org/")>  _
    Partial Public Class getVocationalLicenseResponseResultMessage
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private resultCodeField As Integer
        
        Private resultDescField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property resultCode() As Integer
            Get
                Return Me.resultCodeField
            End Get
            Set
                Me.resultCodeField = value
                Me.RaisePropertyChanged("resultCode")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property resultDesc() As String
            Get
                Return Me.resultDescField
            End Get
            Set
                Me.resultDescField = value
                Me.RaisePropertyChanged("resultDesc")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class getVocationalLicenseRequest1
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public getVocationalLicenseRequest As ServiceReference6.getVocationalLicenseRequest
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal getVocationalLicenseRequest As ServiceReference6.getVocationalLicenseRequest)
            MyBase.New
            Me.getVocationalLicenseRequest = getVocationalLicenseRequest
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class getVocationalLicenseResponse1
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public getVocationalLicenseResponse As ServiceReference6.getVocationalLicenseResponse
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal getVocationalLicenseResponse As ServiceReference6.getVocationalLicenseResponse)
            MyBase.New
            Me.getVocationalLicenseResponse = getVocationalLicenseResponse
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface FreeZonesServiceInterfaceChannel
        Inherits ServiceReference6.FreeZonesServiceInterface, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class FreeZonesServiceInterfaceClient
        Inherits System.ServiceModel.ClientBase(Of ServiceReference6.FreeZonesServiceInterface)
        Implements ServiceReference6.FreeZonesServiceInterface
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference6_FreeZonesServiceInterface_getCommercialRecord(ByVal request As ServiceReference6.getCommercialRecordRequest1) As ServiceReference6.getCommercialRecordResponse1 Implements ServiceReference6.FreeZonesServiceInterface.getCommercialRecord
            Return MyBase.Channel.getCommercialRecord(request)
        End Function
        
        Public Function getCommercialRecord(ByVal getCommercialRecordRequest As ServiceReference6.getCommercialRecordRequest) As ServiceReference6.getCommercialRecordResponse
            Dim inValue As ServiceReference6.getCommercialRecordRequest1 = New ServiceReference6.getCommercialRecordRequest1()
            inValue.getCommercialRecordRequest = getCommercialRecordRequest
            Dim retVal As ServiceReference6.getCommercialRecordResponse1 = CType(Me,ServiceReference6.FreeZonesServiceInterface).getCommercialRecord(inValue)
            Return retVal.getCommercialRecordResponse
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference6_FreeZonesServiceInterface_getCommercialRecordAsync(ByVal request As ServiceReference6.getCommercialRecordRequest1) As System.Threading.Tasks.Task(Of ServiceReference6.getCommercialRecordResponse1) Implements ServiceReference6.FreeZonesServiceInterface.getCommercialRecordAsync
            Return MyBase.Channel.getCommercialRecordAsync(request)
        End Function
        
        Public Function getCommercialRecordAsync(ByVal getCommercialRecordRequest As ServiceReference6.getCommercialRecordRequest) As System.Threading.Tasks.Task(Of ServiceReference6.getCommercialRecordResponse1)
            Dim inValue As ServiceReference6.getCommercialRecordRequest1 = New ServiceReference6.getCommercialRecordRequest1()
            inValue.getCommercialRecordRequest = getCommercialRecordRequest
            Return CType(Me,ServiceReference6.FreeZonesServiceInterface).getCommercialRecordAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference6_FreeZonesServiceInterface_getVocationalLicense(ByVal request As ServiceReference6.getVocationalLicenseRequest1) As ServiceReference6.getVocationalLicenseResponse1 Implements ServiceReference6.FreeZonesServiceInterface.getVocationalLicense
            Return MyBase.Channel.getVocationalLicense(request)
        End Function
        
        Public Function getVocationalLicense(ByVal getVocationalLicenseRequest As ServiceReference6.getVocationalLicenseRequest) As ServiceReference6.getVocationalLicenseResponse
            Dim inValue As ServiceReference6.getVocationalLicenseRequest1 = New ServiceReference6.getVocationalLicenseRequest1()
            inValue.getVocationalLicenseRequest = getVocationalLicenseRequest
            Dim retVal As ServiceReference6.getVocationalLicenseResponse1 = CType(Me,ServiceReference6.FreeZonesServiceInterface).getVocationalLicense(inValue)
            Return retVal.getVocationalLicenseResponse
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference6_FreeZonesServiceInterface_getVocationalLicenseAsync(ByVal request As ServiceReference6.getVocationalLicenseRequest1) As System.Threading.Tasks.Task(Of ServiceReference6.getVocationalLicenseResponse1) Implements ServiceReference6.FreeZonesServiceInterface.getVocationalLicenseAsync
            Return MyBase.Channel.getVocationalLicenseAsync(request)
        End Function
        
        Public Function getVocationalLicenseAsync(ByVal getVocationalLicenseRequest As ServiceReference6.getVocationalLicenseRequest) As System.Threading.Tasks.Task(Of ServiceReference6.getVocationalLicenseResponse1)
            Dim inValue As ServiceReference6.getVocationalLicenseRequest1 = New ServiceReference6.getVocationalLicenseRequest1()
            inValue.getVocationalLicenseRequest = getVocationalLicenseRequest
            Return CType(Me,ServiceReference6.FreeZonesServiceInterface).getVocationalLicenseAsync(inValue)
        End Function
    End Class
End Namespace
