'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace ServiceReference4
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Result", [Namespace]:="http://schemas.datacontract.org/2004/07/MOSDService"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Result
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ADDRESS1Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ASSDT1Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ASSEXP1Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ASSGOAL1Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ASSNAME1Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ASSNOT1Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private BUILDNUM1Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CITY1Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CITY_ID1Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CLASS1Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CLASS_DESC1Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DEPT1Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EMAIL1Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ESSNAME1Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FLTRNAME1Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private GOV1Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private LEWQAD1Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private LNDPHON1Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MBLNO1Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MINISNAME1Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NATNO1Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private POBOX1Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private POSTALCODE1Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SOCOFFICE1Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SOC_TYPE_DESC1Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SOC_TYPE_ID1Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private STREET1Field As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ADDRESS1() As String
            Get
                Return Me.ADDRESS1Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.ADDRESS1Field, value) <> true) Then
                    Me.ADDRESS1Field = value
                    Me.RaisePropertyChanged("ADDRESS1")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ASSDT1() As String
            Get
                Return Me.ASSDT1Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.ASSDT1Field, value) <> true) Then
                    Me.ASSDT1Field = value
                    Me.RaisePropertyChanged("ASSDT1")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ASSEXP1() As String
            Get
                Return Me.ASSEXP1Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.ASSEXP1Field, value) <> true) Then
                    Me.ASSEXP1Field = value
                    Me.RaisePropertyChanged("ASSEXP1")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ASSGOAL1() As String
            Get
                Return Me.ASSGOAL1Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.ASSGOAL1Field, value) <> true) Then
                    Me.ASSGOAL1Field = value
                    Me.RaisePropertyChanged("ASSGOAL1")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ASSNAME1() As String
            Get
                Return Me.ASSNAME1Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.ASSNAME1Field, value) <> true) Then
                    Me.ASSNAME1Field = value
                    Me.RaisePropertyChanged("ASSNAME1")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ASSNOT1() As String
            Get
                Return Me.ASSNOT1Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.ASSNOT1Field, value) <> true) Then
                    Me.ASSNOT1Field = value
                    Me.RaisePropertyChanged("ASSNOT1")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property BUILDNUM1() As String
            Get
                Return Me.BUILDNUM1Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.BUILDNUM1Field, value) <> true) Then
                    Me.BUILDNUM1Field = value
                    Me.RaisePropertyChanged("BUILDNUM1")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CITY1() As String
            Get
                Return Me.CITY1Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.CITY1Field, value) <> true) Then
                    Me.CITY1Field = value
                    Me.RaisePropertyChanged("CITY1")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CITY_ID1() As String
            Get
                Return Me.CITY_ID1Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.CITY_ID1Field, value) <> true) Then
                    Me.CITY_ID1Field = value
                    Me.RaisePropertyChanged("CITY_ID1")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CLASS1() As String
            Get
                Return Me.CLASS1Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.CLASS1Field, value) <> true) Then
                    Me.CLASS1Field = value
                    Me.RaisePropertyChanged("CLASS1")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CLASS_DESC1() As String
            Get
                Return Me.CLASS_DESC1Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.CLASS_DESC1Field, value) <> true) Then
                    Me.CLASS_DESC1Field = value
                    Me.RaisePropertyChanged("CLASS_DESC1")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DEPT1() As String
            Get
                Return Me.DEPT1Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.DEPT1Field, value) <> true) Then
                    Me.DEPT1Field = value
                    Me.RaisePropertyChanged("DEPT1")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property EMAIL1() As String
            Get
                Return Me.EMAIL1Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.EMAIL1Field, value) <> true) Then
                    Me.EMAIL1Field = value
                    Me.RaisePropertyChanged("EMAIL1")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ESSNAME1() As String
            Get
                Return Me.ESSNAME1Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.ESSNAME1Field, value) <> true) Then
                    Me.ESSNAME1Field = value
                    Me.RaisePropertyChanged("ESSNAME1")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FLTRNAME1() As String
            Get
                Return Me.FLTRNAME1Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.FLTRNAME1Field, value) <> true) Then
                    Me.FLTRNAME1Field = value
                    Me.RaisePropertyChanged("FLTRNAME1")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property GOV1() As String
            Get
                Return Me.GOV1Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.GOV1Field, value) <> true) Then
                    Me.GOV1Field = value
                    Me.RaisePropertyChanged("GOV1")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property LEWQAD1() As String
            Get
                Return Me.LEWQAD1Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.LEWQAD1Field, value) <> true) Then
                    Me.LEWQAD1Field = value
                    Me.RaisePropertyChanged("LEWQAD1")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property LNDPHON1() As String
            Get
                Return Me.LNDPHON1Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.LNDPHON1Field, value) <> true) Then
                    Me.LNDPHON1Field = value
                    Me.RaisePropertyChanged("LNDPHON1")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property MBLNO1() As String
            Get
                Return Me.MBLNO1Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.MBLNO1Field, value) <> true) Then
                    Me.MBLNO1Field = value
                    Me.RaisePropertyChanged("MBLNO1")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property MINISNAME1() As String
            Get
                Return Me.MINISNAME1Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.MINISNAME1Field, value) <> true) Then
                    Me.MINISNAME1Field = value
                    Me.RaisePropertyChanged("MINISNAME1")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property NATNO1() As String
            Get
                Return Me.NATNO1Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.NATNO1Field, value) <> true) Then
                    Me.NATNO1Field = value
                    Me.RaisePropertyChanged("NATNO1")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property POBOX1() As String
            Get
                Return Me.POBOX1Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.POBOX1Field, value) <> true) Then
                    Me.POBOX1Field = value
                    Me.RaisePropertyChanged("POBOX1")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property POSTALCODE1() As String
            Get
                Return Me.POSTALCODE1Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.POSTALCODE1Field, value) <> true) Then
                    Me.POSTALCODE1Field = value
                    Me.RaisePropertyChanged("POSTALCODE1")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property SOCOFFICE1() As String
            Get
                Return Me.SOCOFFICE1Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.SOCOFFICE1Field, value) <> true) Then
                    Me.SOCOFFICE1Field = value
                    Me.RaisePropertyChanged("SOCOFFICE1")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property SOC_TYPE_DESC1() As String
            Get
                Return Me.SOC_TYPE_DESC1Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.SOC_TYPE_DESC1Field, value) <> true) Then
                    Me.SOC_TYPE_DESC1Field = value
                    Me.RaisePropertyChanged("SOC_TYPE_DESC1")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property SOC_TYPE_ID1() As String
            Get
                Return Me.SOC_TYPE_ID1Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.SOC_TYPE_ID1Field, value) <> true) Then
                    Me.SOC_TYPE_ID1Field = value
                    Me.RaisePropertyChanged("SOC_TYPE_ID1")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property STREET1() As String
            Get
                Return Me.STREET1Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.STREET1Field, value) <> true) Then
                    Me.STREET1Field = value
                    Me.RaisePropertyChanged("STREET1")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="ServiceReference4.IMOSDSrvV2")>  _
    Public Interface IMOSDSrvV2
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IMOSDSrvV2/GetCSOSMIT", ReplyAction:="http://tempuri.org/IMOSDSrvV2/GetCSOSMITResponse")>  _
        Function GetCSOSMIT(ByVal NATNO As String) As ServiceReference4.Result()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IMOSDSrvV2/GetCSOSMIT", ReplyAction:="http://tempuri.org/IMOSDSrvV2/GetCSOSMITResponse")>  _
        Function GetCSOSMITAsync(ByVal NATNO As String) As System.Threading.Tasks.Task(Of ServiceReference4.Result())
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IMOSDSrvV2Channel
        Inherits ServiceReference4.IMOSDSrvV2, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class MOSDSrvV2Client
        Inherits System.ServiceModel.ClientBase(Of ServiceReference4.IMOSDSrvV2)
        Implements ServiceReference4.IMOSDSrvV2
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function GetCSOSMIT(ByVal NATNO As String) As ServiceReference4.Result() Implements ServiceReference4.IMOSDSrvV2.GetCSOSMIT
            Return MyBase.Channel.GetCSOSMIT(NATNO)
        End Function
        
        Public Function GetCSOSMITAsync(ByVal NATNO As String) As System.Threading.Tasks.Task(Of ServiceReference4.Result()) Implements ServiceReference4.IMOSDSrvV2.GetCSOSMITAsync
            Return MyBase.Channel.GetCSOSMITAsync(NATNO)
        End Function
    End Class
End Namespace
